
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-loudspeaker-ureuzy-github-io-v1alpha1-loudspeaker
  failurePolicy: Fail
  name: mloudspeaker.kb.io
  rules:
  - apiGroups:
    - loudspeaker.ureuzy.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - loudspeakers
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-loudspeaker-ureuzy-github-io-v1alpha1-loudspeaker
  failurePolicy: Fail
  name: vloudspeaker.kb.io
  rules:
  - apiGroups:
    - loudspeaker.ureuzy.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - loudspeakers
  sideEffects: None
