# permissions for end users to view loudspeakers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loudspeaker-viewer-role
rules:
- apiGroups:
  - loudspeaker.ureuzy.github.io
  resources:
  - loudspeakers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - loudspeaker.ureuzy.github.io
  resources:
  - loudspeakers/status
  verbs:
  - get
