name: Test
on:
  pull_request:
    branches:
      - master
    paths:
      - 'api/**'
      - 'config/**'
      - 'controller/**'
      - 'pkg/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Go imports
        run: goimports

      - name: Get dependencies
        run: go get -t .

      - name: Test
        run: make test

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          
  notification:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification on Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON: https://avatars0.githubusercontent.com/u/44036562?s=100&v=4
          SLACK_USERNAME: GitHubActions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON: https://avatars0.githubusercontent.com/u/44036562?s=100&v=4
          SLACK_USERNAME: GitHubActions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
